### ISSUE TITLE
Server Side Doesn't Seem To Host

### ISSUE THREAD

**Issue by blitzfall** [ayushmaanbhav/stockmart#2]
I am testing this locally prior to trying to implement it as a way to do a simulated stock exchange for a political simulation server.

Upon launching and starting the server and then launching the client while running on local host.

java -jar StockMartClient.jar -localhost

I register with the CHKRegNo turned off on the server side. I proceed with valid information, click the register button, and after a second or so I get this error inside the command prompt used to launch the client. 

Don't know about host
java.lang.NullPointerException
        at com.ayushmaanbhav.jstockmart.client.Client.register(Client.java:76)
        at com.ayushmaanbhav.jstockmart.client.RegisterAction$4.run(RegisterAction.java:59)

I should note that I also did try using my local IPV4 found in ipconfig. Neither of those worked.

**Comment by ayushmaanbhav** [comment]
try the new web platform, issues are fixed
